[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]
  included_files = [
    "app/api/create-payment-intent/route.ts",
    "components/PaymentForm.tsx"
  ]

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Credentials = "true"
    Cache-Control = "no-store"
    Pragma = "no-cache"

[context.production]
  environment = { SECRETS_SCAN_ENABLED = "false" }

[functions.next]
  included_files = ["app/api/**/*"]
