[build]
  command = "npm install --prefer-offline && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "true"
  NODE_OPTIONS = "--max_old_space_size=4096"
  SECRETS_SCAN_ENABLED = "false"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

[functions.create-payment-intent]
  included_files = []
  external_node_modules = ["stripe"]

[dev]
  functions = "netlify/functions"
  publish = ".next"
  framework = "#custom"
  targetPort = 3000

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Credentials = "true"
    Cache-Control = "no-store"
    Pragma = "no-cache"
